services:
  nuxbill-local:
    container_name: nuxbill-local
    pull_policy: always
    build: ./
    restart: unless-stopped
    ports:
      - "8080:80"  # Different port for local testing
    environment:
      TZ: Africa/Nairobi
    depends_on:
      - mysql-local
    volumes:
      - ./config.local.php:/var/www/html/config.php  # Use local config

  mysql-local:
    container_name: mysql-local
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: "SecureP@ssw0rd123!"
      MYSQL_DATABASE: "nuxbill_local"
      MYSQL_USER: "nuxbill"
      MYSQL_PASSWORD: "SecureP@ssw0rd123!"
    ports:
      - "3308:3306"  # Different port for local testing
    volumes:
      - mysql_local_data:/var/lib/mysql  # Persistent data for local testing

volumes:
  mysql_local_data: